# Phase 7 — SQL Analysis

This notebook builds and investigates a portable SQLite analytics layer over the five validated Phase 6 summary datasets. Raw, cleaned, and feature CSVs are treated as immutable inputs.

## 1. SQL analysis objectives

The analysis answers practical team, batting, bowling, and toss questions; demonstrates aggregation, joins, CTEs, conditional logic, subqueries, and window functions; and reconciles every core total to Phase 6. Sample thresholds are used for rate rankings so short careers do not produce misleading leaders.

In [1]:
from pathlib import Path
import hashlib
import sys

import pandas as pd
from IPython.display import Markdown, display

candidate = Path.cwd().resolve()
PROJECT_ROOT = candidate if (candidate / 'src').exists() else candidate.parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from src.data_loader import get_data_paths
from src.sql_analysis import (
    ANALYSIS_FILES, TABLE_FILES, connect_database, create_database,
    get_sql_paths, inspect_database, inspect_source_csvs,
    load_analysis_queries, parse_named_queries, query_dataframe,
)

pd.set_option('display.max_columns', 40)
pd.set_option('display.float_format', lambda value: f'{value:,.2f}')
data_paths = get_data_paths(PROJECT_ROOT)
sql_paths = get_sql_paths(PROJECT_ROOT)
protected_paths = [
    data_paths['matches_raw'], data_paths['deliveries_raw'],
    data_paths['matches_clean'], data_paths['deliveries_clean'],
    *[sql_paths['processed'] / filename for filename in TABLE_FILES.values()],
]
sha256 = lambda path: hashlib.sha256(path.read_bytes()).hexdigest()
source_hashes_before = {path.name: sha256(path) for path in protected_paths}
print('Portable project-relative configuration loaded.')

Portable project-relative configuration loaded.

## 2. Database creation and loading

The builder inspects all five CSVs, creates declared SQLite tables in a temporary database, loads the unchanged records, creates views, validates integrity, and atomically publishes the final database. A prior database is inspected before any rebuild.

In [2]:
display(inspect_source_csvs(PROJECT_ROOT))
database_path, database_validation = create_database(PROJECT_ROOT)
print('Database created:', database_path.relative_to(PROJECT_ROOT))
print(f"Build validation: {database_validation['status'].eq('PASS').sum()}/{len(database_validation)} PASS")

,table_name,rows,columns,null_cells,column_names
0,match_summary,1095,33,1146,"match_id, season_label, match_date, city, venu..."
1,innings_summary,2217,17,0,"match_id, season, inning, batting_team, bowlin..."
2,team_season_summary,146,19,0,"season, team, matches_played, decided_matches,..."
3,batting_summary,2617,14,381,"season, batter, matches, runs, balls_faced, fo..."
4,bowling_summary,1948,12,0,"season, bowler, matches, legal_balls, overs_bo..."

Database created: data\processed\ipl_analysis.db
Build validation: 49/49 PASS

## 3. Schema inspection

Natural keys and the match-to-innings relationship are declared in SQLite rather than inferred at query time.

In [3]:
display(inspect_database(database_path))
connection = connect_database(PROJECT_ROOT)
for table in TABLE_FILES:
    display(Markdown(f'**Schema: `{table}`**'))
    display(query_dataframe(connection, f'PRAGMA table_info("{table}")'))

     type                      name
0   index          idx_batting_runs
1   index       idx_bowling_wickets
2   index  idx_innings_batting_team
3   index  idx_innings_bowling_team
4   index  idx_match_summary_season
5   index   idx_match_summary_teams
6   table           batting_summary
7   table           bowling_summary
8   table           innings_summary
9   table             match_summary
10  table       team_season_summary
11   view          v_batting_career
12   view          v_bowling_career
13   view            v_team_overall
14   view          v_toss_by_season

**Schema: `match_summary`**

    cid                         name     type  notnull dflt_value  pk
0     0                     match_id  INTEGER        0       None   1
1     1                 season_label     TEXT        1       None   0
2     2                   match_date     TEXT        1       None   0
3     3                         city     TEXT        1       None   0
4     4                        venue     TEXT        1       None   0
5     5                        team1     TEXT        1       None   0
6     6                        team2     TEXT        1       None   0
7     7                  toss_winner     TEXT        1       None   0
8     8                toss_decision     TEXT        1       None   0
9     9                 winning_team     TEXT        0       None   0
10   10                       result     TEXT        1       None   0
11   11                result_margin     REAL        0       None   0
12   12              player_of_match     TEXT        0       None   0
13   13                   match_type     TEXT        1       None   0
14   14                   super_over     TEXT        1       None   0
15   15                       method     TEXT        0       None   0
16   16                match_decided  INTEGER        1       None   0
17   17  toss_winner_is_match_winner  INTEGER        0       None   0
18   18                  losing_team     TEXT        0       None   0
19   19              win_margin_type     TEXT        0       None   0
20   20                  match_stage     TEXT        1       None   0
21   21                innings_count  INTEGER        1       None   0
22   22    match_recorded_deliveries  INTEGER        1       None   0
23   23            match_legal_balls  INTEGER        1       None   0
24   24     match_illegal_deliveries  INTEGER        1       None   0
25   25             match_total_runs  INTEGER        1       None   0
26   26           match_batsman_runs  INTEGER        1       None   0
27   27             match_extra_runs  INTEGER        1       None   0
28   28                match_wickets  INTEGER        1       None   0
29   29         match_bowler_wickets  INTEGER        1       None   0
30   30                  match_fours  INTEGER        1       None   0
31   31                  match_sixes  INTEGER        1       None   0
32   32              match_dot_balls  INTEGER        1       None   0

**Schema: `innings_summary`**

    cid                 name     type  notnull dflt_value  pk
0     0             match_id  INTEGER        1       None   1
1     1               season     TEXT        1       None   0
2     2               inning  INTEGER        1       None   2
3     3         batting_team     TEXT        1       None   0
4     4         bowling_team     TEXT        1       None   0
5     5  recorded_deliveries  INTEGER        1       None   0
6     6          legal_balls  INTEGER        1       None   0
7     7   illegal_deliveries  INTEGER        1       None   0
8     8           total_runs  INTEGER        1       None   0
9     9         batsman_runs  INTEGER        1       None   0
10   10           extra_runs  INTEGER        1       None   0
11   11              wickets  INTEGER        1       None   0
12   12       bowler_wickets  INTEGER        1       None   0
13   13                fours  INTEGER        1       None   0
14   14                sixes  INTEGER        1       None   0
15   15            dot_balls  INTEGER        1       None   0
16   16             run_rate     REAL        1       None   0

**Schema: `team_season_summary`**

    cid                          name     type  notnull dflt_value  pk
0     0                        season     TEXT        1       None   1
1     1                          team     TEXT        1       None   2
2     2                matches_played  INTEGER        1       None   0
3     3               decided_matches  INTEGER        1       None   0
4     4                          wins  INTEGER        1       None   0
5     5                        losses  INTEGER        1       None   0
6     6                          ties  INTEGER        1       None   0
7     7                    no_results  INTEGER        1       None   0
8     8                win_percentage     REAL        1       None   0
9     9             total_runs_scored  INTEGER        1       None   0
10   10           total_runs_conceded  INTEGER        1       None   0
11   11           average_runs_scored     REAL        1       None   0
12   12         average_runs_conceded     REAL        1       None   0
13   13           total_wickets_taken  INTEGER        1       None   0
14   14            total_wickets_lost  INTEGER        1       None   0
15   15                     toss_wins  INTEGER        1       None   0
16   16          toss_decided_matches  INTEGER        1       None   0
17   17               toss_match_wins  INTEGER        1       None   0
18   18  toss_to_match_win_percentage     REAL        1       None   0

**Schema: `batting_summary`**

    cid                 name     type  notnull dflt_value  pk
0     0               season     TEXT        1       None   1
1     1               batter     TEXT        1       None   2
2     2              matches  INTEGER        1       None   0
3     3                 runs  INTEGER        1       None   0
4     4          balls_faced  INTEGER        1       None   0
5     5                fours  INTEGER        1       None   0
6     6                sixes  INTEGER        1       None   0
7     7        boundary_runs  INTEGER        1       None   0
8     8            dot_balls  INTEGER        1       None   0
9     9           dismissals  INTEGER        1       None   0
10   10          strike_rate     REAL        1       None   0
11   11      batting_average     REAL        0       None   0
12   12  boundary_percentage     REAL        0       None   0
13   13  dot_ball_percentage     REAL        1       None   0

**Schema: `bowling_summary`**

    cid                 name     type  notnull dflt_value  pk
0     0               season     TEXT        1       None   1
1     1               bowler     TEXT        1       None   2
2     2              matches  INTEGER        1       None   0
3     3          legal_balls  INTEGER        1       None   0
4     4         overs_bowled     REAL        1       None   0
5     5        runs_conceded  INTEGER        1       None   0
6     6              wickets  INTEGER        1       None   0
7     7         economy_rate     REAL        1       None   0
8     8            dot_balls  INTEGER        1       None   0
9     9  dot_ball_percentage     REAL        1       None   0
10   10                wides  INTEGER        1       None   0
11   11             no_balls  INTEGER        1       None   0

## 4. Table row counts

The database grain must exactly match each Phase 6 CSV.

In [4]:
reconciliation_queries = parse_named_queries(sql_paths['reconciliation'])
row_counts = query_dataframe(connection, reconciliation_queries['table_row_counts'])
display(row_counts)

            table_name  row_count
0        match_summary       1095
1      innings_summary       2217
2  team_season_summary        146
3      batting_summary       2617
4      bowling_summary       1948

## 5. Data-quality checks

SQLite integrity, foreign keys, row counts, cross-table totals, all named queries, and the query inventory are checked centrally.

In [5]:
display(database_validation)
assert database_validation['status'].eq('PASS').all()
queries = load_analysis_queries(PROJECT_ROOT)
query_count = sum(len(items) for items in queries.values())
print(f'Named analytical queries: {query_count}')
assert query_count == 30

                                                check status    actual
0                              SQLite integrity check   PASS        ok
1                                   Foreign-key check   PASS         0
2                             match_summary row count   PASS      1095
3                           innings_summary row count   PASS      2217
4                       team_season_summary row count   PASS       146
5                           batting_summary row count   PASS      2617
6                           bowling_summary row count   PASS      1948
7                              matches reconciliation   PASS      1095
8                           total_runs reconciliation   PASS    347756
9                          batter_runs reconciliation   PASS    330064
10                              extras reconciliation   PASS     17692
11                         legal_balls reconciliation   PASS    251471
12               bowler_credit_wickets reconciliation   PASS     11815
13            Team runs scored reconcile with innings   PASS     equal
14          Team runs conceded reconcile with innings   PASS     equal
15                Batting runs reconcile with innings   PASS     equal
16         Bowling legal balls reconcile with innings   PASS     equal
17                Team wickets reconcile with bowlers   PASS     equal
18  SQL executes: 01_team_performance.sql/teams_by...   PASS  executed
19  SQL executes: 01_team_performance.sql/qualifie...   PASS  executed
20  SQL executes: 01_team_performance.sql/team_mat...   PASS  executed
21  SQL executes: 01_team_performance.sql/team_sea...   PASS  executed
22  SQL executes: 01_team_performance.sql/qualifie...   PASS  executed
23  SQL executes: 01_team_performance.sql/stronges...   PASS  executed
24  SQL executes: 02_batting_analysis.sql/top_15_r...   PASS  executed
25  SQL executes: 02_batting_analysis.sql/qualifie...   PASS  executed
26   SQL executes: 02_batting_analysis.sql/most_fours   PASS  executed
27   SQL executes: 02_batting_analysis.sql/most_sixes   PASS  executed
28  SQL executes: 02_batting_analysis.sql/qualifie...   PASS  executed
29  SQL executes: 02_batting_analysis.sql/top_run_...   PASS  executed
30  SQL executes: 02_batting_analysis.sql/high_vol...   PASS  executed
31  SQL executes: 03_bowling_analysis.sql/top_15_w...   PASS  executed
32  SQL executes: 03_bowling_analysis.sql/qualifie...   PASS  executed
33  SQL executes: 03_bowling_analysis.sql/top_wick...   PASS  executed
34  SQL executes: 03_bowling_analysis.sql/high_wic...   PASS  executed
35  SQL executes: 03_bowling_analysis.sql/most_leg...   PASS  executed
36  SQL executes: 03_bowling_analysis.sql/stronges...   PASS  executed
37  SQL executes: 04_toss_analysis.sql/overall_tos...   PASS  executed
38  SQL executes: 04_toss_analysis.sql/qualified_t...   PASS  executed
39  SQL executes: 04_toss_analysis.sql/qualified_t...   PASS  executed
40  SQL executes: 04_toss_analysis.sql/toss_relati...   PASS  executed
41  SQL executes: 04_toss_analysis.sql/team_toss_w...   PASS  executed
42  SQL executes: 05_advanced_analysis.sql/team_ra...   PASS  executed
43  SQL executes: 05_advanced_analysis.sql/batter_...   PASS  executed
44  SQL executes: 05_advanced_analysis.sql/bowler_...   PASS  executed
45  SQL executes: 05_advanced_analysis.sql/top_bat...   PASS  executed
46  SQL executes: 05_advanced_analysis.sql/team_vs...   PASS  executed
47  SQL executes: 05_advanced_analysis.sql/team_wi...   PASS  executed
48                           Analysis query inventory   PASS        30

Named analytical queries: 30

In [6]:
def show_query(filename, name, question, interpretation, rows=15):
    query = queries[filename][name]
    result = query_dataframe(connection, query)
    display(Markdown(f'### {question}'))
    display(Markdown(f'```sql\n{query}\n```'))
    display(result.head(rows))
    display(Markdown(f'**Interpretation:** {interpretation}'))
    return result

## 6. Team performance analysis

Career totals, qualified percentages, season detail, scoring pace, and a transparent multi-metric profile are considered together.

In [7]:
team_wins = show_query('01_team_performance.sql', 'teams_by_total_wins', 'Which teams have the most total wins?', 'Mumbai Indians lead with 142 wins; totals measure longevity as well as performance.')
team_win_rate = show_query('01_team_performance.sql', 'qualified_teams_by_win_percentage', 'Which established teams have the highest win percentage?', 'Among teams with at least 50 decided matches, Chennai Super Kings lead at 58.47%.')
team_matches = show_query('01_team_performance.sql', 'team_matches_played', 'How many matches did each team play?', 'Participation totals use both match-team positions and preserve ties and no-results.')
team_seasons = show_query('01_team_performance.sql', 'team_season_performance', 'How did each team perform season by season?', 'The complete result supports season filters; rankings should retain each season’s different match volume.', rows=20)
team_scoring = show_query('01_team_performance.sql', 'qualified_teams_by_scoring_rate', 'Which teams have the highest aggregate scoring rate?', 'With at least 3,000 legal balls, Gujarat Titans lead at 8.83 runs per six legal balls; their shorter history still matters.')
team_profiles = show_query('01_team_performance.sql', 'strongest_overall_team_profiles', 'Which teams have the strongest overall statistical profiles?', 'The transparent four-rank composite places Mumbai Indians first and Chennai Super Kings second; it is not an official rating.')

### Which teams have the most total wins?

```sql
SELECT team, matches_played, wins, losses, ties, no_results, win_percentage
FROM v_team_overall
ORDER BY wins DESC, win_percentage DESC, team
LIMIT 15
```

,team,matches_played,wins,losses,ties,no_results,win_percentage
0,Mumbai Indians,261,142,115,4,0,55.25
1,Chennai Super Kings,238,138,98,1,1,58.47
2,Kolkata Knight Riders,251,130,117,4,0,52.63
3,Royal Challengers Bengaluru,255,121,128,3,3,48.59
4,Delhi Capitals,252,112,134,4,2,45.53
5,Rajasthan Royals,221,110,106,3,2,50.93
6,Punjab Kings,246,109,133,4,0,45.04
7,Sunrisers Hyderabad,182,87,91,4,0,48.88
8,Deccan Chargers,75,29,46,0,0,38.67
9,Gujarat Titans,45,28,17,0,0,62.22
10,Lucknow Super Giants,44,24,19,0,1,55.81
11,Rising Pune Supergiant,30,15,15,0,0,50.00
12,Gujarat Lions,30,13,16,1,0,44.83
13,Pune Warriors,46,12,33,0,1,26.67
14,Kochi Tuskers Kerala,14,6,8,0,0,42.86

**Interpretation:** Mumbai Indians lead with 142 wins; totals measure longevity as well as performance.

### Which established teams have the highest win percentage?

```sql
SELECT team, decided_matches, wins, losses, win_percentage
FROM v_team_overall
WHERE decided_matches >= 50
ORDER BY win_percentage DESC, wins DESC, team
```

                          team  decided_matches  wins  losses  win_percentage
0          Chennai Super Kings              236   138      98           58.47
1               Mumbai Indians              257   142     115           55.25
2        Kolkata Knight Riders              247   130     117           52.63
3             Rajasthan Royals              216   110     106           50.93
4          Sunrisers Hyderabad              178    87      91           48.88
5  Royal Challengers Bengaluru              249   121     128           48.59
6               Delhi Capitals              246   112     134           45.53
7                 Punjab Kings              242   109     133           45.04
8              Deccan Chargers               75    29      46           38.67

**Interpretation:** Among teams with at least 50 decided matches, Chennai Super Kings lead at 58.47%.

### How many matches did each team play?

```sql
SELECT team, matches_played, decided_matches, ties, no_results
FROM v_team_overall
ORDER BY matches_played DESC, team
```

,team,matches_played,decided_matches,ties,no_results
0,Mumbai Indians,261,257,4,0
1,Royal Challengers Bengaluru,255,249,3,3
2,Delhi Capitals,252,246,4,2
3,Kolkata Knight Riders,251,247,4,0
4,Punjab Kings,246,242,4,0
5,Chennai Super Kings,238,236,1,1
6,Rajasthan Royals,221,216,3,2
7,Sunrisers Hyderabad,182,178,4,0
8,Deccan Chargers,75,75,0,0
9,Pune Warriors,46,45,0,1
10,Gujarat Titans,45,45,0,0
11,Lucknow Super Giants,44,43,0,1
12,Gujarat Lions,30,29,1,0
13,Rising Pune Supergiant,30,30,0,0
14,Kochi Tuskers Kerala,14,14,0,0

**Interpretation:** Participation totals use both match-team positions and preserve ties and no-results.

### How did each team perform season by season?

```sql
SELECT
    season, team, matches_played, wins, losses, ties, no_results,
    ROUND(win_percentage, 2) AS win_percentage,
    total_runs_scored, total_runs_conceded, total_wickets_taken
FROM team_season_summary
ORDER BY season, wins DESC, win_percentage DESC, team
```

,season,team,matches_played,wins,losses,ties,no_results,win_percentage,total_runs_scored,total_runs_conceded,total_wickets_taken
0,2007/08,Rajasthan Royals,16,13,3,0,0,81.25,2601,2403,96
1,2007/08,Punjab Kings,15,10,5,0,0,66.67,2464,2417,83
2,2007/08,Chennai Super Kings,16,9,7,0,0,56.25,2520,2568,83
3,2007/08,Delhi Capitals,14,7,7,0,0,50.00,2118,2223,82
4,2007/08,Mumbai Indians,14,7,7,0,0,50.00,2080,2096,83
5,2007/08,Kolkata Knight Riders,13,6,7,0,0,46.15,1942,1718,61
6,2007/08,Royal Challengers Bengaluru,14,4,10,0,0,28.57,1983,2205,56
7,2007/08,Deccan Chargers,14,2,12,0,0,14.29,2229,2307,60
8,2009,Delhi Capitals,15,10,5,0,0,66.67,2131,2158,91
9,2009,Deccan Chargers,16,9,7,0,0,56.25,2408,2387,97
10,2009,Royal Challengers Bengaluru,16,9,7,0,0,56.25,2280,2316,79
11,2009,Chennai Super Kings,14,8,6,0,0,57.14,2231,2004,84
12,2009,Punjab Kings,14,7,7,0,0,50.00,1928,1886,71
13,2009,Rajasthan Royals,13,5,7,1,0,41.67,1706,1825,79
14,2009,Mumbai Indians,13,5,8,0,0,38.46,1897,1802,72
15,2009,Kolkata Knight Riders,13,3,9,1,0,25.00,1772,1975,49
16,2009/10,Mumbai Indians,16,11,5,0,0,68.75,2738,2417,86
17,2009/10,Chennai Super Kings,16,9,6,1,0,60.00,2604,2517,90
18,2009/10,Deccan Chargers,16,8,8,0,0,50.00,2374,2482,93
19,2009/10,Royal Challengers Bengaluru,16,8,8,0,0,50.00,2401,2511,81

**Interpretation:** The complete result supports season filters; rankings should retain each season’s different match volume.

### Which teams have the highest aggregate scoring rate?

```sql
WITH team_scoring AS (
    SELECT
        batting_team AS team,
        SUM(total_runs) AS runs,
        SUM(legal_balls) AS legal_balls
    FROM innings_summary
    GROUP BY batting_team
)
SELECT
    team,
    runs,
    legal_balls,
    ROUND(6.0 * runs / NULLIF(legal_balls, 0), 2) AS scoring_rate
FROM team_scoring
WHERE legal_balls >= 3000
ORDER BY scoring_rate DESC, runs DESC, team
```

                           team   runs  legal_balls  scoring_rate
0                Gujarat Titans   7757         5270          8.83
1          Lucknow Super Giants   7510         5151          8.75
2                 Gujarat Lions   4862         3439          8.48
3   Royal Challengers Bengaluru  40622        28943          8.42
4           Chennai Super Kings  38629        27626          8.39
5                Mumbai Indians  42176        30250          8.37
6                  Punjab Kings  39600        28429          8.36
7         Kolkata Knight Riders  39331        28385          8.31
8           Sunrisers Hyderabad  29071        21053          8.29
9              Rajasthan Royals  34747        25316          8.24
10               Delhi Capitals  39196        28708          8.19
11       Rising Pune Supergiant   4533         3364          8.09
12              Deccan Chargers  11463         8752          7.86
13                Pune Warriors   6358         5275          7.23

**Interpretation:** With at least 3,000 legal balls, Gujarat Titans lead at 8.83 runs per six legal balls; their shorter history still matters.

### Which teams have the strongest overall statistical profiles?

```sql
WITH scoring AS (
    SELECT batting_team AS team, SUM(total_runs) AS runs, SUM(legal_balls) AS legal_balls
    FROM innings_summary
    GROUP BY batting_team
), eligible AS (
    SELECT
        t.team, t.seasons_played, t.matches_played, t.wins, t.decided_matches,
        t.win_percentage, t.total_wickets_taken,
        ROUND(6.0 * s.runs / NULLIF(s.legal_balls, 0), 2) AS scoring_rate
    FROM v_team_overall AS t
    JOIN scoring AS s ON s.team = t.team
    WHERE t.decided_matches >= 50
), ranked AS (
    SELECT *,
        RANK() OVER (ORDER BY wins DESC) AS wins_rank,
        RANK() OVER (ORDER BY win_percentage DESC) AS win_rate_rank,
        RANK() OVER (ORDER BY scoring_rate DESC) AS scoring_rank,
        RANK() OVER (ORDER BY total_wickets_taken DESC) AS wickets_rank
    FROM eligible
)
SELECT *,
    ROUND((wins_rank + win_rate_rank + scoring_rank + wickets_rank) / 4.0, 2)
        AS composite_rank_score
FROM ranked
ORDER BY composite_rank_score, win_rate_rank, wins_rank, team
```

,team,seasons_played,matches_played,wins,decided_matches,win_percentage,total_wickets_taken,scoring_rate,wins_rank,win_rate_rank,scoring_rank,wickets_rank,composite_rank_score
0,Mumbai Indians,17,261,142,257,55.25,1458,8.37,1,2,3,1,1.75
1,Chennai Super Kings,15,238,138,236,58.47,1361,8.39,2,1,2,3,2.00
2,Royal Challengers Bengaluru,17,255,121,249,48.59,1364,8.42,4,6,1,2,3.25
3,Kolkata Knight Riders,17,251,130,247,52.63,1333,8.31,3,3,5,5,4.00
4,Rajasthan Royals,15,221,110,216,50.93,1155,8.24,6,4,7,7,6.00
5,Delhi Capitals,17,252,112,246,45.53,1347,8.19,5,7,8,4,6.00
6,Punjab Kings,17,246,109,242,45.04,1298,8.36,7,8,4,6,6.25
7,Sunrisers Hyderabad,12,182,87,178,48.88,984,8.29,8,5,6,8,6.75
8,Deccan Chargers,5,75,29,75,38.67,408,7.86,9,9,9,9,9.00

**Interpretation:** The transparent four-rank composite places Mumbai Indians first and Chennai Super Kings second; it is not an official rating.

## 7. Batting analysis

Career measures are recomputed from summed numerators and denominators. Rate and average leaderboards use explicit minimum samples.

In [8]:
bat_runs = show_query('02_batting_analysis.sql', 'top_15_run_scorers', 'Who are the top 15 run scorers?', 'V Kohli leads with 8,014 runs.')
bat_sr = show_query('02_batting_analysis.sql', 'qualified_strike_rate_leaders', 'Who has the highest qualified strike rate?', 'AD Russell leads at 174.84 among batters with at least 1,000 balls faced.')
bat_fours = show_query('02_batting_analysis.sql', 'most_fours', 'Who hit the most fours?', 'This ranks boundary events, with career runs used only as a tie-breaker.')
bat_sixes = show_query('02_batting_analysis.sql', 'most_sixes', 'Who hit the most sixes?', 'This is an event-volume ranking and should be read alongside career opportunity.')
bat_avg = show_query('02_batting_analysis.sql', 'qualified_batting_average_leaders', 'Who has the highest qualified batting average?', 'KL Rahul leads at 44.66 with the minimum set at 50 supported dismissals.')
bat_season = show_query('02_batting_analysis.sql', 'top_run_scorers_by_season', 'Who were the top run scorers in each season?', 'RANK preserves tied run totals and returns the top three ranks per season.', rows=20)
bat_combo = show_query('02_batting_analysis.sql', 'high_volume_high_strike_rate_batters', 'Who combines high run volume with high strike rate?', 'Among batters with 2,000 runs and 1,000 balls, AB de Villiers has the best average of run and strike-rate ranks.')

### Who are the top 15 run scorers?

```sql
SELECT batter, runs, balls_faced, dismissals, strike_rate, batting_average
FROM v_batting_career
ORDER BY runs DESC, strike_rate DESC, batter
LIMIT 15
```

,batter,runs,balls_faced,dismissals,strike_rate,batting_average
0,V Kohli,8014,6069,207,132.05,38.71
1,S Dhawan,6769,5326,192,127.09,35.26
2,RG Sharma,6630,5057,223,131.11,29.73
3,DA Warner,6567,4702,164,139.66,40.04
4,SK Raina,5536,4046,171,136.83,32.37
5,MS Dhoni,5243,3812,134,137.54,39.13
6,AB de Villiers,5181,3411,130,151.89,39.85
7,CH Gayle,4997,3346,126,149.34,39.66
8,RV Uthappa,4954,3801,180,130.33,27.52
9,KD Karthik,4843,3580,184,135.28,26.32
10,KL Rahul,4689,3485,105,134.55,44.66
11,AM Rahane,4642,3761,154,123.42,30.14
12,F du Plessis,4571,3352,127,136.37,35.99
13,SV Samson,4419,3180,144,138.96,30.69
14,AT Rayudu,4348,3409,154,127.54,28.23

**Interpretation:** V Kohli leads with 8,014 runs.

### Who has the highest qualified strike rate?

```sql
SELECT batter, runs, balls_faced, strike_rate, boundary_percentage
FROM v_batting_career
WHERE balls_faced >= 1000
ORDER BY strike_rate DESC, runs DESC, batter
LIMIT 15
```

            batter  runs  balls_faced  strike_rate  boundary_percentage
0       AD Russell  2488         1423       174.84                77.89
1         N Pooran  1769         1092       162.00                68.63
2       GJ Maxwell  2772         1769       156.70                68.25
3         V Sehwag  2728         1755       155.44                72.29
4   AB de Villiers  5181         3411       151.89                61.26
5      YBK Jaiswal  1607         1067       150.61                73.43
6         CH Gayle  4997         3346       149.34                75.77
7          RR Pant  3297         2215       148.85                64.18
8       KA Pollard  3437         2329       147.57                64.82
9          PP Shaw  1892         1283       147.47                69.66
10      JC Buttler  3583         2430       147.45                66.70
11          S Dube  1502         1024       146.68                63.25
12       HH Pandya  2534         1739       145.72                62.27
13        SA Yadav  3594         2474       145.27                64.55
14     JM Bairstow  1589         1100       144.45                67.84

**Interpretation:** AD Russell leads at 174.84 among batters with at least 1,000 balls faced.

### Who hit the most fours?

```sql
SELECT batter, runs, fours, boundary_percentage
FROM v_batting_career
ORDER BY fours DESC, runs DESC, batter
LIMIT 15
```

            batter  runs  fours  boundary_percentage
0         S Dhawan  6769    768                58.95
1          V Kohli  8014    708                55.78
2        DA Warner  6567    663                61.95
3        RG Sharma  6630    599                61.57
4         SK Raina  5536    506                58.67
5        G Gambhir  4217    492                55.06
6       RV Uthappa  4954    481                60.88
7        AM Rahane  4642    479                54.59
8       KD Karthik  4843    466                58.43
9     F du Plessis  4571    422                58.72
10  AB de Villiers  5181    414                61.26
11        CH Gayle  4997    408                75.77
12        KL Rahul  4689    400                58.05
13        SA Yadav  3594    385                64.55
14       SR Watson  3880    377                68.25

**Interpretation:** This ranks boundary events, with career runs used only as a tie-breaker.

### Who hit the most sixes?

```sql
SELECT batter, runs, sixes, boundary_percentage
FROM v_batting_career
ORDER BY sixes DESC, runs DESC, batter
LIMIT 15
```

            batter  runs  sixes  boundary_percentage
0         CH Gayle  4997    359                75.77
1        RG Sharma  6630    281                61.57
2          V Kohli  8014    273                55.78
3   AB de Villiers  5181    253                61.26
4         MS Dhoni  5243    252                56.53
5        DA Warner  6567    236                61.95
6       KA Pollard  3437    224                64.82
7       AD Russell  2488    209                77.89
8        SV Samson  4419    206                59.83
9         SK Raina  5536    204                58.67
10       SR Watson  3880    190                68.25
11        KL Rahul  4689    187                58.05
12      RV Uthappa  4954    182                60.88
13       AT Rayudu  4348    173                56.90
14    F du Plessis  4571    166                58.72

**Interpretation:** This is an event-volume ranking and should be read alongside career opportunity.

### Who has the highest qualified batting average?

```sql
SELECT batter, runs, dismissals, batting_average, strike_rate
FROM v_batting_career
WHERE dismissals >= 50
ORDER BY batting_average DESC, runs DESC, batter
LIMIT 15
```

            batter  runs  dismissals  batting_average  strike_rate
0         KL Rahul  4689         105            44.66       134.55
1       RD Gaikwad  2380          57            41.75       136.86
2        DA Warner  6567         164            40.04       139.66
3   AB de Villiers  5181         130            39.85       151.89
4        JP Duminy  2029          51            39.78       124.02
5         CH Gayle  4997         126            39.66       149.34
6         SE Marsh  2489          63            39.51       133.03
7         MS Dhoni  5243         134            39.13       137.54
8       MEK Hussey  1977          51            38.76       122.64
9          V Kohli  8014         207            38.71       132.05
10    Shubman Gill  3216          85            37.84       135.70
11      JC Buttler  3583          95            37.72       147.45
12       DA Miller  2924          81            36.10       139.17
13    F du Plessis  4571         127            35.99       136.37
14   KS Williamson  2132          60            35.53       125.63

**Interpretation:** KL Rahul leads at 44.66 with the minimum set at 50 supported dismissals.

### Who were the top run scorers in each season?

```sql
WITH ranked AS (
    SELECT
        season, batter, runs, balls_faced, strike_rate,
        RANK() OVER (PARTITION BY season ORDER BY runs DESC) AS season_run_rank
    FROM batting_summary
)
SELECT season, season_run_rank, batter, runs, balls_faced, ROUND(strike_rate, 2) AS strike_rate
FROM ranked
WHERE season_run_rank <= 3
ORDER BY season, season_run_rank, batter
```

     season  season_run_rank          batter  runs  balls_faced  strike_rate
0   2007/08                1        SE Marsh   616          441       139.68
1   2007/08                2       G Gambhir   534          379       140.90
2   2007/08                3   ST Jayasuriya   514          309       166.34
3      2009                1       ML Hayden   572          395       144.81
4      2009                2    AC Gilchrist   495          325       152.31
5      2009                3  AB de Villiers   465          355       130.99
6   2009/10                1    SR Tendulkar   618          466       132.62
7   2009/10                2       JH Kallis   572          494       115.79
8   2009/10                3        SK Raina   528          367       143.87
9      2011                1        CH Gayle   608          332       183.13
10     2011                2         V Kohli   557          460       121.09
11     2011                3    SR Tendulkar   553          488       113.32
12     2012                1        CH Gayle   733          456       160.75
13     2012                2       G Gambhir   590          411       143.55
14     2012                3        S Dhawan   569          439       129.61
15     2013                1      MEK Hussey   733          566       129.51
16     2013                2        CH Gayle   720          459       156.86
17     2013                3         V Kohli   639          459       139.22
18     2014                1      RV Uthappa   660          479       137.79
19     2014                2        DR Smith   566          416       136.06

**Interpretation:** RANK preserves tied run totals and returns the top three ranks per season.

### Who combines high run volume with high strike rate?

```sql
WITH qualified AS (
    SELECT *
    FROM v_batting_career
    WHERE runs >= 2000 AND balls_faced >= 1000
), ranked AS (
    SELECT *,
        RANK() OVER (ORDER BY runs DESC) AS run_rank,
        RANK() OVER (ORDER BY strike_rate DESC) AS strike_rate_rank
    FROM qualified
)
SELECT
    batter, runs, balls_faced, strike_rate, batting_average,
    run_rank, strike_rate_rank,
    ROUND((run_rank + strike_rate_rank) / 2.0, 2) AS combined_rank_score
FROM ranked
ORDER BY combined_rank_score, runs DESC, batter
LIMIT 20
```

,batter,runs,balls_faced,strike_rate,batting_average,run_rank,strike_rate_rank,combined_rank_score
0,AB de Villiers,5181,3411,151.89,39.85,7,4,5.50
1,CH Gayle,4997,3346,149.34,39.66,8,5,6.50
2,DA Warner,6567,4702,139.66,40.04,4,12,8.00
3,MS Dhoni,5243,3812,137.54,39.13,6,18,12.00
4,SK Raina,5536,4046,136.83,32.37,5,20,12.50
5,JC Buttler,3583,2430,147.45,37.72,20,8,14.00
6,KA Pollard,3437,2329,147.57,28.40,21,7,14.00
7,RR Pant,3297,2215,148.85,35.45,22,6,14.00
8,SV Samson,4419,3180,138.96,30.69,14,15,14.50
9,SA Yadav,3594,2474,145.27,31.81,19,10,14.50
10,V Kohli,8014,6069,132.05,38.71,1,31,16.00
11,KD Karthik,4843,3580,135.28,26.32,10,24,17.00
12,F du Plessis,4571,3352,136.37,35.99,13,21,17.00
13,SR Watson,3880,2813,137.93,30.79,17,17,17.00
14,YK Pathan,3222,2245,143.52,29.29,23,11,17.00

**Interpretation:** Among batters with 2,000 runs and 1,000 balls, AB de Villiers has the best average of run and strike-rate ranks.

## 8. Bowling analysis

Economy uses legal balls and bowler-chargeable runs. Wickets exclude run outs and other non-bowler dismissals.

In [9]:
bowl_wickets = show_query('03_bowling_analysis.sql', 'top_15_wicket_takers', 'Who are the top 15 wicket takers?', 'YS Chahal leads the documented bowler-credit convention with 205 wickets.')
bowl_econ = show_query('03_bowling_analysis.sql', 'qualified_economy_leaders', 'Who has the best qualified economy?', 'M Muralitharan leads at 6.70 among bowlers with at least 1,200 legal balls.')
bowl_season = show_query('03_bowling_analysis.sql', 'top_wicket_takers_by_season', 'Who took the most wickets by season?', 'RANK preserves ties among the top three wicket ranks in every season.', rows=20)
bowl_combo = show_query('03_bowling_analysis.sql', 'high_wicket_good_economy_bowlers', 'Who combines 100 wickets with good economy?', 'The 100-wicket threshold balances sustained wicket volume with career economy.')
bowl_balls = show_query('03_bowling_analysis.sql', 'most_legal_balls_bowled', 'Who bowled the most legal balls?', 'Legal-ball workload is shown directly, with six-ball-equivalent overs for readability.')
bowl_profiles = show_query('03_bowling_analysis.sql', 'strongest_overall_bowling_profiles', 'Who has the strongest overall statistical bowling profile?', 'The wickets/economy/dot-ball composite highlights balanced careers but is not an official player rating.')

### Who are the top 15 wicket takers?

```sql
SELECT bowler, wickets, legal_balls, economy_rate, dot_ball_percentage
FROM v_bowling_career
ORDER BY wickets DESC, economy_rate, bowler
LIMIT 15
```

             bowler  wickets  legal_balls  economy_rate  dot_ball_percentage
0         YS Chahal      205         3521          7.84                33.91
1         PP Chawla      192         3850          7.96                34.42
2          DJ Bravo      183         3120          8.38                31.99
3           B Kumar      181         3910          7.56                41.74
4         SP Narine      180         4081          6.74                38.45
5          R Ashwin      180         4524          7.12                34.31
6          A Mishra      174         3371          7.38                35.15
7        SL Malinga      170         2828          7.14                40.45
8         JJ Bumrah      168         3075          7.30                39.93
9         RA Jadeja      160         3829          7.62                31.76
10  Harbhajan Singh      150         3416          7.08                36.97
11      Rashid Khan      149         2872          6.83                36.91
12         UT Yadav      144         3057          8.50                38.80
13   Sandeep Sharma      137         2822          7.89                39.76
14         HV Patel      135         2162          8.74                32.84

**Interpretation:** YS Chahal leads the documented bowler-credit convention with 205 wickets.

### Who has the best qualified economy?

```sql
SELECT bowler, legal_balls, wickets, economy_rate, dot_ball_percentage
FROM v_bowling_career
WHERE legal_balls >= 1200
ORDER BY economy_rate, wickets DESC, bowler
LIMIT 15
```

             bowler  legal_balls  wickets  economy_rate  dot_ball_percentage
0    M Muralitharan         1528       64          6.70                39.27
1         SP Narine         4081      180          6.74                38.45
2       Rashid Khan         2872      149          6.83                36.91
3          DW Steyn         2182       97          6.94                46.70
4   Harbhajan Singh         3416      150          7.08                36.97
5          R Ashwin         4524      180          7.12                34.31
6        SL Malinga         2828      170          7.14                40.45
7          AR Patel         3105      123          7.27                32.88
8         JJ Bumrah         3075      168          7.30                39.93
9           PP Ojha         1899       89          7.37                35.12
10        KH Pandya         2122       76          7.37                31.86
11         A Mishra         3371      174          7.38                35.15
12         R Bhatia         1636       71          7.41                26.65
13  Shakib Al Hasan         1484       63          7.44                33.96
14         MM Patel         1355       74          7.52                43.54

**Interpretation:** M Muralitharan leads at 6.70 among bowlers with at least 1,200 legal balls.

### Who took the most wickets by season?

```sql
WITH ranked AS (
    SELECT
        season, bowler, wickets, legal_balls, economy_rate,
        RANK() OVER (PARTITION BY season ORDER BY wickets DESC) AS season_wicket_rank
    FROM bowling_summary
)
SELECT season, season_wicket_rank, bowler, wickets, legal_balls, ROUND(economy_rate, 2) AS economy_rate
FROM ranked
WHERE season_wicket_rank <= 3
ORDER BY season, season_wicket_rank, bowler
```

,season,season_wicket_rank,bowler,wickets,legal_balls,economy_rate
0,2007/08,1,Sohail Tanvir,22,247,6.46
1,2007/08,2,S Sreesanth,19,307,8.64
2,2007/08,2,SK Warne,19,312,7.77
3,2009,1,RP Singh,23,358,6.99
4,2009,2,A Kumble,21,355,5.86
5,2009,3,A Nehra,19,306,6.78
6,2009/10,1,PP Ojha,21,353,7.29
7,2009/10,2,A Kumble,17,380,6.43
8,2009/10,2,A Mishra,17,318,6.85
9,2009/10,2,Harbhajan Singh,17,321,7.05
10,2011,1,SL Malinga,28,378,5.95
11,2011,2,MM Patel,22,326,6.59
12,2011,3,S Aravind,21,276,8.00
13,2012,1,M Morkel,25,378,7.19
14,2012,2,SP Narine,24,355,5.48
15,2012,3,SL Malinga,22,333,6.31
16,2013,1,DJ Bravo,32,375,7.95
17,2013,2,JP Faulkner,28,379,6.76
18,2013,3,Harbhajan Singh,24,420,6.51
19,2013,3,MG Johnson,24,384,7.17

**Interpretation:** RANK preserves ties among the top three wicket ranks in every season.

### Who combines 100 wickets with good economy?

```sql
SELECT bowler, wickets, legal_balls, economy_rate, dot_ball_percentage
FROM v_bowling_career
WHERE wickets >= 100
ORDER BY economy_rate, wickets DESC, bowler
```

             bowler  wickets  legal_balls  economy_rate  dot_ball_percentage
0         SP Narine      180         4081          6.74                38.45
1       Rashid Khan      149         2872          6.83                36.91
2   Harbhajan Singh      150         3416          7.08                36.97
3          R Ashwin      180         4524          7.12                34.31
4        SL Malinga      170         2828          7.14                40.45
5          AR Patel      123         3105          7.27                32.88
6         JJ Bumrah      168         3075          7.30                39.93
7          A Mishra      174         3371          7.38                35.15
8           B Kumar      181         3910          7.56                41.74
9            Z Khan      102         2200          7.59                39.68
10        RA Jadeja      160         3829          7.62                31.76
11        YS Chahal      205         3521          7.84                33.91
12          A Nehra      106         1908          7.85                41.82
13   Sandeep Sharma      137         2822          7.89                39.76
14        PP Chawla      192         3850          7.96                34.42

**Interpretation:** The 100-wicket threshold balances sustained wicket volume with career economy.

### Who bowled the most legal balls?

```sql
SELECT bowler, legal_balls, overs_bowled, wickets, economy_rate
FROM v_bowling_career
ORDER BY legal_balls DESC, wickets DESC, bowler
LIMIT 15
```

             bowler  legal_balls  overs_bowled  wickets  economy_rate
0          R Ashwin         4524        754.00      180          7.12
1         SP Narine         4081        680.17      180          6.74
2           B Kumar         3910        651.67      181          7.56
3         PP Chawla         3850        641.67      192          7.96
4         RA Jadeja         3829        638.17      160          7.62
5         YS Chahal         3521        586.83      205          7.84
6   Harbhajan Singh         3416        569.33      150          7.08
7          A Mishra         3371        561.83      174          7.38
8          DJ Bravo         3120        520.00      183          8.38
9          AR Patel         3105        517.50      123          7.27
10        JJ Bumrah         3075        512.50      168          7.30
11         UT Yadav         3057        509.50      144          8.50
12      Rashid Khan         2872        478.67      149          6.83
13       SL Malinga         2828        471.33      170          7.14
14   Sandeep Sharma         2822        470.33      137          7.89

**Interpretation:** Legal-ball workload is shown directly, with six-ball-equivalent overs for readability.

### Who has the strongest overall statistical bowling profile?

```sql
WITH qualified AS (
    SELECT * FROM v_bowling_career WHERE legal_balls >= 1200
), ranked AS (
    SELECT *,
        RANK() OVER (ORDER BY wickets DESC) AS wicket_rank,
        RANK() OVER (ORDER BY economy_rate) AS economy_rank,
        RANK() OVER (ORDER BY dot_ball_percentage DESC) AS dot_rank
    FROM qualified
)
SELECT
    bowler, wickets, legal_balls, economy_rate, dot_ball_percentage,
    wicket_rank, economy_rank, dot_rank,
    ROUND((wicket_rank + economy_rank + dot_rank) / 3.0, 2) AS composite_rank_score
FROM ranked
ORDER BY composite_rank_score, wicket_rank, bowler
LIMIT 20
```

,bowler,wickets,legal_balls,economy_rate,dot_ball_percentage,wicket_rank,economy_rank,dot_rank,composite_rank_score
0,SL Malinga,170,2828,7.14,40.45,8,7,16,10.33
1,DW Steyn,97,2182,6.94,46.70,26,4,1,10.33
2,B Kumar,181,3910,7.56,41.74,4,17,11,10.67
3,SP Narine,180,4081,6.74,38.45,5,2,28,11.67
4,JJ Bumrah,168,3075,7.30,39.93,9,9,19,12.33
5,Harbhajan Singh,150,3416,7.08,36.97,11,5,31,15.67
6,Rashid Khan,149,2872,6.83,36.91,12,3,32,15.67
7,A Mishra,174,3371,7.38,35.15,7,12,39,19.33
8,R Ashwin,180,4524,7.12,34.31,5,6,48,19.67
9,A Nehra,106,1908,7.85,41.82,22,29,10,20.33
10,P Kumar,90,2524,7.73,42.59,32,24,5,20.33
11,Sandeep Sharma,137,2822,7.89,39.76,14,30,21,21.67
12,Z Khan,102,2200,7.59,39.68,24,19,22,21.67
13,MM Patel,74,1355,7.52,43.54,48,15,2,21.67
14,M Morkel,77,1629,7.69,43.46,41,22,3,22.00

**Interpretation:** The wickets/economy/dot-ball composite highlights balanced careers but is not an official player rating.

## 9. Toss analysis

Only ordinary runs/wickets outcomes enter win comparisons. These are descriptive associations and do not establish causality.

In [10]:
toss_overall = show_query('04_toss_analysis.sql', 'overall_toss_winner_match_win_rate', 'How often did the toss winner also win?', 'Toss winners also won 548 of 1,076 eligible matches (50.93%); this does not imply causation.')
toss_win = show_query('04_toss_analysis.sql', 'qualified_team_toss_win_percentage', 'Which teams won the toss most often relative to matches played?', 'Only teams with at least 50 matches are ranked to reduce small-sample distortion.')
toss_convert = show_query('04_toss_analysis.sql', 'qualified_team_toss_to_match_win_percentage', 'Which teams most often converted eligible toss wins into match wins?', 'Chennai Super Kings lead at 62.50% across 120 eligible toss wins.')
toss_season = show_query('04_toss_analysis.sql', 'toss_relationship_by_season', 'How did the toss relationship vary by season?', 'Season percentages fluctuate and should be interpreted as descriptive context.', rows=20)
toss_difference = show_query('04_toss_analysis.sql', 'team_toss_win_rate_difference', 'Which teams show the largest toss-win versus toss-loss difference?', 'The percentage-point difference requires 20 observations in each group and remains non-causal.')

### How often did the toss winner also win?

```sql
SELECT
    COUNT(*) AS eligible_matches,
    SUM(CASE WHEN toss_winner = winning_team THEN 1 ELSE 0 END) AS toss_winner_match_wins,
    ROUND(100.0 * SUM(CASE WHEN toss_winner = winning_team THEN 1 ELSE 0 END) / COUNT(*), 2)
        AS toss_winner_match_win_percentage
FROM match_summary
WHERE result IN ('runs', 'wickets')
```

   eligible_matches  toss_winner_match_wins  toss_winner_match_win_percentage
0              1076                     548                             50.93

**Interpretation:** Toss winners also won 548 of 1,076 eligible matches (50.93%); this does not imply causation.

### Which teams won the toss most often relative to matches played?

```sql
SELECT
    team, matches_played, toss_wins,
    ROUND(100.0 * toss_wins / NULLIF(matches_played, 0), 2) AS toss_win_percentage
FROM v_team_overall
WHERE matches_played >= 50
ORDER BY toss_win_percentage DESC, toss_wins DESC, team
```

                          team  matches_played  toss_wins  toss_win_percentage
0              Deccan Chargers              75         43                57.33
1               Mumbai Indians             261        143                54.79
2             Rajasthan Royals             221        120                54.30
3               Delhi Capitals             252        130                51.59
4          Chennai Super Kings             238        122                51.26
5        Kolkata Knight Riders             251        122                48.61
6          Sunrisers Hyderabad             182         88                48.35
7  Royal Challengers Bengaluru             255        121                47.45
8                 Punjab Kings             246        109                44.31

**Interpretation:** Only teams with at least 50 matches are ranked to reduce small-sample distortion.

### Which teams most often converted eligible toss wins into match wins?

```sql
SELECT
    team, toss_decided_matches, toss_match_wins, toss_to_match_win_percentage
FROM v_team_overall
WHERE toss_decided_matches >= 25
ORDER BY toss_to_match_win_percentage DESC, toss_match_wins DESC, team
```

,team,toss_decided_matches,toss_match_wins,toss_to_match_win_percentage
0,Chennai Super Kings,120,75,62.50
1,Kolkata Knight Riders,121,68,56.20
2,Mumbai Indians,140,77,55.00
3,Royal Challengers Bengaluru,118,60,50.85
4,Rajasthan Royals,117,59,50.43
5,Delhi Capitals,127,59,46.46
6,Deccan Chargers,43,19,44.19
7,Sunrisers Hyderabad,87,38,43.68
8,Punjab Kings,107,44,41.12

**Interpretation:** Chennai Super Kings lead at 62.50% across 120 eligible toss wins.

### How did the toss relationship vary by season?

```sql
SELECT season, eligible_matches, toss_winner_match_wins, toss_winner_match_win_percentage
FROM v_toss_by_season
ORDER BY season
```

,season,eligible_matches,toss_winner_match_wins,toss_winner_match_win_percentage
0,2007/08,58,28,48.28
1,2009,56,33,58.93
2,2009/10,59,31,52.54
3,2011,72,38,52.78
4,2012,74,33,44.59
5,2013,74,35,47.30
6,2014,59,29,49.15
7,2015,56,27,48.21
8,2016,60,34,56.67
9,2017,58,34,58.62
10,2018,60,32,53.33
11,2019,57,34,59.65
12,2020/21,56,25,44.64
13,2021,59,34,57.63
14,2022,74,36,48.65
15,2023,73,34,46.58
16,2024,71,31,43.66

**Interpretation:** Season percentages fluctuate and should be interpreted as descriptive context.

### Which teams show the largest toss-win versus toss-loss difference?

```sql
WITH participation AS (
    SELECT match_id, team1 AS team, toss_winner, winning_team
    FROM match_summary WHERE result IN ('runs', 'wickets')
    UNION ALL
    SELECT match_id, team2 AS team, toss_winner, winning_team
    FROM match_summary WHERE result IN ('runs', 'wickets')
), team_split AS (
    SELECT
        team,
        SUM(CASE WHEN team = toss_winner THEN 1 ELSE 0 END) AS toss_won_matches,
        SUM(CASE WHEN team = toss_winner AND team = winning_team THEN 1 ELSE 0 END) AS wins_after_toss_win,
        SUM(CASE WHEN team <> toss_winner THEN 1 ELSE 0 END) AS toss_lost_matches,
        SUM(CASE WHEN team <> toss_winner AND team = winning_team THEN 1 ELSE 0 END) AS wins_after_toss_loss
    FROM participation
    GROUP BY team
)
SELECT
    team, toss_won_matches, wins_after_toss_win,
    ROUND(100.0 * wins_after_toss_win / NULLIF(toss_won_matches, 0), 2) AS win_rate_after_toss_win,
    toss_lost_matches, wins_after_toss_loss,
    ROUND(100.0 * wins_after_toss_loss / NULLIF(toss_lost_matches, 0), 2) AS win_rate_after_toss_loss,
    ROUND(
        100.0 * wins_after_toss_win / NULLIF(toss_won_matches, 0)
        - 100.0 * wins_after_toss_loss / NULLIF(toss_lost_matches, 0), 2
    ) AS descriptive_percentage_point_difference
FROM team_split
WHERE toss_won_matches >= 20 AND toss_lost_matches >= 20
ORDER BY descriptive_percentage_point_difference DESC, team
```

,team,toss_won_matches,wins_after_toss_win,win_rate_after_toss_win,toss_lost_matches,wins_after_toss_loss,win_rate_after_toss_loss,descriptive_percentage_point_difference
0,Deccan Chargers,43,19,44.19,32,10,31.25,12.94
1,Chennai Super Kings,120,75,62.50,116,63,54.31,8.19
2,Kolkata Knight Riders,121,68,56.20,126,62,49.21,6.99
3,Royal Challengers Bengaluru,118,60,50.85,131,61,46.56,4.28
4,Gujarat Titans,22,14,63.64,23,14,60.87,2.77
5,Delhi Capitals,127,59,46.46,119,53,44.54,1.92
6,Mumbai Indians,140,77,55.00,117,65,55.56,-0.56
7,Rajasthan Royals,117,59,50.43,99,51,51.52,-1.09
8,Punjab Kings,107,44,41.12,135,65,48.15,-7.03
9,Sunrisers Hyderabad,87,38,43.68,91,49,53.85,-10.17
10,Pune Warriors,20,3,15.00,25,9,36.00,-21.00

**Interpretation:** The percentage-point difference requires 20 observations in each group and remains non-causal.

## 10. Advanced SQL and window functions

The queries below demonstrate season partitions, tied ranks, deterministic top rows, season-average comparisons, and lagged team results.

In [11]:
advanced_context = {
    'team_rank_within_season': ('How do teams rank within each season?', 'RANK uses wins then win percentage within each season.'),
    'batter_rank_within_season': ('How do batters rank by season runs?', 'The season partition prevents cross-season volume comparisons.'),
    'bowler_rank_within_season': ('How do bowlers rank by season wickets?', 'Tied wicket totals receive the same rank.'),
    'top_batter_each_season': ('Who is the deterministic top run scorer in each season?', 'ROW_NUMBER selects one row using strike rate and name as tie-breakers.'),
    'team_vs_season_average': ('Which teams were above their season average?', 'A window average supplies context without collapsing team rows.'),
    'team_wins_year_over_year': ('How did team win totals change from their prior recorded season?', 'LAG compares adjacent recorded seasons; schedule size and missed seasons remain limitations.'),
}
advanced_results = {}
for query_name, (question, interpretation) in advanced_context.items():
    advanced_results[query_name] = show_query('05_advanced_analysis.sql', query_name, question, interpretation, rows=18)

### How do teams rank within each season?

```sql
SELECT
    season, team, matches_played, wins, win_percentage,
    RANK() OVER (
        PARTITION BY season
        ORDER BY wins DESC, win_percentage DESC
    ) AS season_team_rank
FROM team_season_summary
ORDER BY season, season_team_rank, team
```

,season,team,matches_played,wins,win_percentage,season_team_rank
0,2007/08,Rajasthan Royals,16,13,81.25,1
1,2007/08,Punjab Kings,15,10,66.67,2
2,2007/08,Chennai Super Kings,16,9,56.25,3
3,2007/08,Delhi Capitals,14,7,50.00,4
4,2007/08,Mumbai Indians,14,7,50.00,4
5,2007/08,Kolkata Knight Riders,13,6,46.15,6
6,2007/08,Royal Challengers Bengaluru,14,4,28.57,7
7,2007/08,Deccan Chargers,14,2,14.29,8
8,2009,Delhi Capitals,15,10,66.67,1
9,2009,Deccan Chargers,16,9,56.25,2
10,2009,Royal Challengers Bengaluru,16,9,56.25,2
11,2009,Chennai Super Kings,14,8,57.14,4
12,2009,Punjab Kings,14,7,50.00,5
13,2009,Rajasthan Royals,13,5,41.67,6
14,2009,Mumbai Indians,13,5,38.46,7
15,2009,Kolkata Knight Riders,13,3,25.00,8
16,2009/10,Mumbai Indians,16,11,68.75,1
17,2009/10,Chennai Super Kings,16,9,60.00,2

**Interpretation:** RANK uses wins then win percentage within each season.

### How do batters rank by season runs?

```sql
SELECT
    season, batter, runs, strike_rate,
    RANK() OVER (PARTITION BY season ORDER BY runs DESC) AS season_run_rank
FROM batting_summary
ORDER BY season, season_run_rank, batter
```

     season         batter  runs  strike_rate  season_run_rank
0   2007/08       SE Marsh   616       139.68                1
1   2007/08      G Gambhir   534       140.90                2
2   2007/08  ST Jayasuriya   514       166.34                3
3   2007/08      SR Watson   472       151.77                4
4   2007/08       GC Smith   441       121.82                5
5   2007/08   AC Gilchrist   436       137.11                6
6   2007/08      YK Pathan   435       179.01                7
7   2007/08       SK Raina   421       142.71                8
8   2007/08       MS Dhoni   414       133.55                9
9   2007/08       V Sehwag   406       184.55               10
10  2007/08      RG Sharma   404       147.99               11
11  2007/08       R Dravid   371       124.50               12
12  2007/08     SC Ganguly   349       113.68               13
13  2007/08       S Dhawan   340       115.25               14
14  2007/08  KC Sangakkara   320       161.62               15
15  2007/08     RV Uthappa   320       114.70               15
16  2007/08      DJ Hussey   319       123.17               17
17  2007/08    SA Asnodkar   311       133.48               18

**Interpretation:** The season partition prevents cross-season volume comparisons.

### How do bowlers rank by season wickets?

```sql
SELECT
    season, bowler, wickets, economy_rate,
    RANK() OVER (PARTITION BY season ORDER BY wickets DESC) AS season_wicket_rank
FROM bowling_summary
ORDER BY season, season_wicket_rank, bowler
```

     season         bowler  wickets  economy_rate  season_wicket_rank
0   2007/08  Sohail Tanvir       22          6.46                   1
1   2007/08    S Sreesanth       19          8.64                   2
2   2007/08       SK Warne       19          7.77                   2
3   2007/08      JA Morkel       17          8.31                   4
4   2007/08        MS Gony       17          7.38                   4
5   2007/08      PP Chawla       17          8.31                   4
6   2007/08      SR Watson       17          7.07                   4
7   2007/08      VY Mahesh       16          8.77                   8
8   2007/08      IK Pathan       15          6.60                   9
9   2007/08    MF Maharoof       15          6.92                   9
10  2007/08       RP Singh       15          8.61                   9
11  2007/08       MM Patel       14          7.64                  12
12  2007/08     SK Trivedi       13          8.31                  13
13  2007/08         Z Khan       13          8.50                  13
14  2007/08        A Nehra       12          7.76                  15
15  2007/08     GD McGrath       12          6.61                  15
16  2007/08       Umar Gul       12          8.18                  15
17  2007/08       A Mishra       11          6.96                  18

**Interpretation:** Tied wicket totals receive the same rank.

### Who is the deterministic top run scorer in each season?

```sql
WITH ranked AS (
    SELECT
        season, batter, runs, strike_rate,
        ROW_NUMBER() OVER (
            PARTITION BY season
            ORDER BY runs DESC, strike_rate DESC, batter
        ) AS row_number_in_season
    FROM batting_summary
)
SELECT season, batter, runs, ROUND(strike_rate, 2) AS strike_rate
FROM ranked
WHERE row_number_in_season = 1
ORDER BY season
```

     season         batter  runs  strike_rate
0   2007/08       SE Marsh   616       139.68
1      2009      ML Hayden   572       144.81
2   2009/10   SR Tendulkar   618       132.62
3      2011       CH Gayle   608       183.13
4      2012       CH Gayle   733       160.75
5      2013     MEK Hussey   733       129.51
6      2014     RV Uthappa   660       137.79
7      2015      DA Warner   562       156.55
8      2016        V Kohli   973       152.03
9      2017      DA Warner   641       141.81
10     2018  KS Williamson   735       142.44
11     2019      DA Warner   692       143.87
12  2020/21       KL Rahul   676       129.01
13     2021     RD Gaikwad   635       136.27
14     2022     JC Buttler   863       149.05
15     2023   Shubman Gill   890       157.80
16     2024        V Kohli   741       154.70

**Interpretation:** ROW_NUMBER selects one row using strike rate and name as tie-breakers.

### Which teams were above their season average?

```sql
WITH compared AS (
    SELECT
        season, team, wins, win_percentage,
        ROUND(AVG(win_percentage) OVER (PARTITION BY season), 2) AS season_average_win_percentage
    FROM team_season_summary
)
SELECT *,
    ROUND(win_percentage - season_average_win_percentage, 2) AS percentage_points_vs_season_average,
    CASE
        WHEN win_percentage > season_average_win_percentage THEN 'Above season average'
        WHEN win_percentage < season_average_win_percentage THEN 'Below season average'
        ELSE 'At season average'
    END AS comparison
FROM compared
ORDER BY season, percentage_points_vs_season_average DESC, team
```

,season,team,wins,win_percentage,season_average_win_percentage,percentage_points_vs_season_average,comparison
0,2007/08,Rajasthan Royals,13,81.25,49.15,32.10,Above season average
1,2007/08,Punjab Kings,10,66.67,49.15,17.52,Above season average
2,2007/08,Chennai Super Kings,9,56.25,49.15,7.10,Above season average
3,2007/08,Delhi Capitals,7,50.00,49.15,0.85,Above season average
4,2007/08,Mumbai Indians,7,50.00,49.15,0.85,Above season average
5,2007/08,Kolkata Knight Riders,6,46.15,49.15,-3.00,Below season average
6,2007/08,Royal Challengers Bengaluru,4,28.57,49.15,-20.58,Below season average
7,2007/08,Deccan Chargers,2,14.29,49.15,-34.86,Below season average
8,2009,Delhi Capitals,10,66.67,48.93,17.74,Above season average
9,2009,Chennai Super Kings,8,57.14,48.93,8.21,Above season average
10,2009,Deccan Chargers,9,56.25,48.93,7.32,Above season average
11,2009,Royal Challengers Bengaluru,9,56.25,48.93,7.32,Above season average
12,2009,Punjab Kings,7,50.00,48.93,1.07,Above season average
13,2009,Rajasthan Royals,5,41.67,48.93,-7.26,Below season average
14,2009,Mumbai Indians,5,38.46,48.93,-10.47,Below season average
15,2009,Kolkata Knight Riders,3,25.00,48.93,-23.93,Below season average
16,2009/10,Mumbai Indians,11,68.75,49.34,19.41,Above season average
17,2009/10,Chennai Super Kings,9,60.00,49.34,10.66,Above season average

**Interpretation:** A window average supplies context without collapsing team rows.

### How did team win totals change from their prior recorded season?

```sql
WITH sequenced AS (
    SELECT
        season, team, wins,
        LAG(wins) OVER (
            PARTITION BY team
            ORDER BY CAST(SUBSTR(season, 1, 4) AS INTEGER), season
        ) AS previous_season_wins
    FROM team_season_summary
)
SELECT
    season, team, wins, previous_season_wins,
    wins - previous_season_wins AS change_in_wins
FROM sequenced
ORDER BY team, CAST(SUBSTR(season, 1, 4) AS INTEGER), season
```

     season                 team  wins  previous_season_wins  change_in_wins
0   2007/08  Chennai Super Kings     9                   NaN             NaN
1      2009  Chennai Super Kings     8                  9.00           -1.00
2   2009/10  Chennai Super Kings     9                  8.00            1.00
3      2011  Chennai Super Kings    11                  9.00            2.00
4      2012  Chennai Super Kings    10                 11.00           -1.00
5      2013  Chennai Super Kings    12                 10.00            2.00
6      2014  Chennai Super Kings    10                 12.00           -2.00
7      2015  Chennai Super Kings    10                 10.00            0.00
8      2018  Chennai Super Kings    11                 10.00            1.00
9      2019  Chennai Super Kings    10                 11.00           -1.00
10  2020/21  Chennai Super Kings     6                 10.00           -4.00
11     2021  Chennai Super Kings    11                  6.00            5.00
12     2022  Chennai Super Kings     4                 11.00           -7.00
13     2023  Chennai Super Kings    10                  4.00            6.00
14     2024  Chennai Super Kings     7                 10.00           -3.00
15  2007/08      Deccan Chargers     2                   NaN             NaN
16     2009      Deccan Chargers     9                  2.00            7.00
17  2009/10      Deccan Chargers     8                  9.00           -1.00

**Interpretation:** LAG compares adjacent recorded seasons; schedule size and missed seasons remain limitations.

## 11. Reconciliation against Phase 6

These anchors test the full SQL load rather than isolated sample results.

In [12]:
totals = query_dataframe(connection, reconciliation_queries['reconciliation_totals'])
expected = {'matches': 1095, 'total_runs': 347756, 'batter_runs': 330064, 'extras': 17692, 'legal_balls': 251471, 'bowler_credit_wickets': 11815}
comparison = pd.DataFrame({
    'metric': list(expected),
    'sql_result': [int(totals.loc[0, key]) for key in expected],
    'phase_6_anchor': list(expected.values()),
})
comparison['difference'] = comparison['sql_result'] - comparison['phase_6_anchor']
comparison['status'] = comparison['difference'].eq(0).map({True: 'PASS', False: 'FAIL'})
display(comparison)
assert comparison['status'].eq('PASS').all()

                  metric  sql_result  phase_6_anchor  difference status
0                matches        1095            1095           0   PASS
1             total_runs      347756          347756           0   PASS
2            batter_runs      330064          330064           0   PASS
3                 extras       17692           17692           0   PASS
4            legal_balls      251471          251471           0   PASS
5  bowler_credit_wickets       11815           11815           0   PASS

## 12. Key findings

- Mumbai Indians have the most wins (142); Chennai Super Kings lead qualified career win percentage (58.47%).
- V Kohli leads runs (8,014), AD Russell leads qualified strike rate (174.84), and KL Rahul leads qualified batting average (44.66).
- YS Chahal leads bowler-credit wickets (205); M Muralitharan leads qualified economy (6.70).
- Toss winners also won 50.93% of the 1,076 ordinary decided matches. This is descriptive, not causal.
- All conclusions are conditional on the documented Phase 4 identity mappings, Phase 6 cricket conventions, and Phase 7 sample thresholds.

## 13. Limitations

Player names are not stable IDs; player match counts are role appearances rather than squad appearances; super overs remain included; historical franchise identity follows the existing standardization; composite ranks depend on selected dimensions; and toss comparisons cannot establish causal effects.

## 14. Source integrity and conclusion

The final hash comparison verifies that database generation did not alter any raw, cleaned, or Phase 6 analytical CSV.

In [13]:
source_hashes_after = {path.name: sha256(path) for path in protected_paths}
integrity = pd.DataFrame({
    'source_file': list(source_hashes_before),
    'unchanged': [source_hashes_before[name] == source_hashes_after[name] for name in source_hashes_before],
})
display(integrity)
assert integrity['unchanged'].all()
connection.close()
print('Phase 7 SQL analysis completed successfully.')
print('Tableau work has not started.')

               source_file  unchanged
0              matches.csv       True
1           deliveries.csv       True
2        matches_clean.csv       True
3     deliveries_clean.csv       True
4        match_summary.csv       True
5      innings_summary.csv       True
6  team_season_summary.csv       True
7      batting_summary.csv       True
8      bowling_summary.csv       True

Phase 7 SQL analysis completed successfully.
Tableau work has not started.